### PR TITLE
Fix Orion Editor Dependency

### PR DESCRIPTION
**Pull request by lharzenetter**
This fix depends on #95.

Deprecated links to the orion editor are fixed. They are now downloaded using maven because they are zipped an not plain text files anymore.

### CODE REVIEW

**Comment by koppor** [comment]
Please rebase on the master branch.

**Comment by koppor** [comment]
This is OK for a first fix.

Could you please check whether `http://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/orion/drops/R-8.0-201502161823/built-editor.zip` can be changed to an URL hosted by the Eclipse software foundation in a follow up.

The 404 of http://www.eclipse.org/orion/editor/releases/current/built-editor.min.js is filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=521644. Let's see, whether the URL comes back.

**Comment by lharzenetter** [comment]
Using the "Main Download Site" link listed in the [list of mirrors](https://www.eclipse.org/downloads/download.php?file=/orion/drops/R-8.0-201502161823/built-editor.zip), the file is not hosted at eclipse but here: http://eclipsemirror.itemis.de/eclipse/orion/drops/R-8.0-201502161823/built-editor.zip

However, there are some German providers hosting this file (e.g. University of Applied Sciences Esslingen, or University of Erlangen-Nuremberg). Should we change the link to one of them or what do you prefer?

**Comment by koppor** [comment]
Why is it `R-8.0-201502161823` and not something from 2017?

Please use the main download site:

grafik

The link is: https://www.eclipse.org/downloads/download.php?file=/orion/drops/R-8.0-201502161823/built-editor.zip&mirror_id=1 - I know that it redirects to itemis currently. Since mirrors may change, but the main download site will be there for a long time, I prefer the main download site.

**Comment by koppor** [comment]
I think, the latest version is http://download.eclipse.org/orion/drops/R-15.1-201706291452/index.html --> http://download.eclipse.org/orion/drops/R-15.1-201706291452/download.php?dropFile=built-editor.zip

Found via http://download.eclipse.org/orion/

**Comment by lharzenetter** [comment]
Yes, but the latest version is not running right now because of some requirejs issue we face right now.

**Pull request merged**
