### PR TITLE
Generate Third-Party section for NOTICE from third-party-libraries.xlsx

### PR DESCRIPTION
**Pull request by Vogel612**
Generated update for NOTICE file's third-party content section using the third-party-libraries EXCEL sheet from #203

### CODE REVIEW

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by koppor** [comment]
In general, the project name should be used. Is that possible? --> The current NOTICE file is generated using https://www.eclipse.org/projects/tools/about.php?id=soa.winery. So, a generated NOTICE file with our tooling should not be too different.

**Comment by Vogel612** [comment]
AFAICT the notice generation tool from eclipse uses information that's not maintained in the third-party-libraries.xlsx. They refer to "human readable" Project Names, which are possibly maintained through the CQ process. There's currently no support for that in the dependency analysis tool, especially considering that this information is not given or maintained in the input file...

We could definitely extend the tool to attempt something like that, but at this point I'd consider that redundant work, given the Foundation apparently maintains such a list matching dependencies to "clearnames".

**Comment by koppor** [comment]
Then our Excel format is wrong. We need to introduce a column "Project Name" After column B, where the user of the Excel sheet has to input the human readable project name.

The Eclipse Software Foundation also requests a "Description", but I would say that we maintain that in Eclipse only.

Example from IP Zilla

```
Name:           Embedded Architectural Decision Records Version 1.0.0
Description:    Allows for embedding architectural decision records in Java code.
```

In our "Project Name" field, we enter the name **without version**

**Comment by Vogel612** [comment]
Updated with the project names used by the Eclipse Foundation, where known from the experimental [legal documents generator](https://www.eclipse.org/projects/tools/about.php?id=soa.winery). 

Also removed certain Angular-Dependencies that are only required for testing, as well as winery-component interdependencies from the generated NOTICE. The latter were also removed from the Excel-Sheet

**Comment by Vogel612** [comment]
PR is stale and outdated. closing

**Pull request closed without merging**
