### PR TITLE
Use shallow clone in docker

### PR DESCRIPTION
**Pull request by abitrolly**
- [x] Ensure that you followed our [toolchain guide](https://github.com/eclipse/winery/blob/main/docs/dev/github-workflow.md#github---prepare-final-pull-request). Especially, we require **a single commit**
- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files
- [ ] Ensure that you appear in `NOTICE` at Copyright Holders
- [ ] Tests created for changes
- [ ] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by lharzenetter** [comment]
We cannot merge your PR. Please read the [contribution guidelines](https://github.com/eclipse/winery/blob/main/CONTRIBUTING.md) carefully.

**Comment by abitrolly** [comment]
@lharzenetter I don't see what's wrong. Test were failing. I signed the ECA, not they pass. What else did I miss?

**Comment by lharzenetter** [comment]
You must sign-off the commit.
https://github.com/eclipse/winery/blob/main/CONTRIBUTING.md#making-the-commit

**Comment by abitrolly** [comment]
The commit was signed by PGP. Anyway, it is fixed now. Why not to automate checking for Signed-Off the same way ECA is checked?

**Comment by abitrolly** [comment]
> Ensure that you followed our toolchain guide. Especially, we require a single commit
>> Before commencing these steps, check with your supervisor

I don't have a supervisor, so I guess this check is marked. It is a single commit.

> Ensure that the commit message is a good commit message

Read 15 pages to select proper verbs and nouns for just such minor change? Isn't it good enough?

>  Ensure that you appear in NOTICE at Copyright Holders

I don't get what is it, and why I should appear here. Probably for those with supervisor.

> Tests created for changes

I don't know how to test that, except manually.

Everything else is not related. Should I check it?




>

**Comment by lharzenetter** [comment]
> The commit was signed by PGP

It's not about signing the commit, its about verifying that you did the changes yourself.

> Ensure that you appear in NOTICE at Copyright Holders

You must add yourself in https://github.com/eclipse/winery/blob/main/NOTICE
Thus, add the line `Copyright (c) 2022 Anatoli Babenia` after the others in the file.

**Comment by abitrolly** [comment]
@lharzenetter I want the credit for such a small change. Can I release this change to be in public domain without `NOTICE`?

**Comment by abitrolly** [comment]
Thanks. Fixed.

What do you think about opening an issue for automating Signed-Off and NOTICE check with CI?

**Comment by lharzenetter** [comment]
That's a good idea!
While googeling real quick, [I found that we no longer need the sign-off}(https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html), but the issue with the `NOTICE` file still stands. However, instead of the sign-off, we would need to check it against the author and the `also-by`/`co-authored-by` footers.

**Pull request merged**
