### PR TITLE
Angular App for the Repository

### PR DESCRIPTION
**Pull request by lharzenetter**
We replaced the frontend with an angular app and adjusted the backend to support json, in order to have a proper rest service for the new frontend.

Signed-off:
- Lukas Harzenetter <lharzenetter@gmx.de>
- Niko Stadelmaier <nstadelmaier.dev@gmail.com>
- Tino Stadelmaier <tstadelmaier.github@gmail.com>
- Lukas Balzer <balzer814_dev@web.de>
- Philipp Meyer <meyer.github@gmail.com>
- Nicole Keppler <keppler1github@gmail.com>
- Huixin Liu <liuhuixin89@gmail.com>

### CODE REVIEW

**Comment by koppor** [comment]
- [ ] Please add following paragraph by @lharzenetter to `docs/dev/index.md` (rendered at http://eclipse.github.io/winery/dev/) or another appropriate place.

> The repository-ui documentation is generated during `npm run build` process and can be found in `org.eclipse.winery.repository.ui/dist/doc` folder.

**Comment by lharzenetter** [comment]
I cannot check the checkbox in your comment @koppor, but i added it, as well as some first documentation

**Comment by koppor** [comment]
Thank you for the PR. I submitted 8886ba1 as [CQ 13942](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13942).

**Comment by koppor** [comment]
The PR was updated to remove a copyrighted figure and minor code improvements appeared on a code review today.

**Comment by koppor** [comment]
Thank you for the PR. I submitted 6449f3c as update [CQ 13942](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13942).

**Comment by koppor** [comment]
Checkin based on Parallel IP allowed.

**Pull request merged**
