### PR TITLE
Add Markdown-Parser + Readme.component for ArtifactTemplates

### PR DESCRIPTION
**Pull request by meyerpp**
Signed-off-by: Philipp Meyer <meyer.github@gmail.com>

Add Markdown-Parser Module to render markdown text in HTML

Add Readme-Component to visualize Readme.md file of ArtifactTemplate-Source-Folder.
 - Preview-Mode
 - Edit-Mode consisting of
   - Edit file in textView
   - Preview changes
   - Both modes 

Use of additional Library:
 angular2-markdown : https://www.npmjs.com/package/angular2-markdown

grafik

grafik

### CODE REVIEW

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by koppor** [comment]
ok to test

**Comment by koppor** [comment]
Code of this PR is using CSS code from angular2-markdown - https://github.com/dimpu/angular2-markdown/blob/1c36831d2c9f48ddd7183db33e886ed9ab0a3345/demo/src/app/home/home.component.ts#L11

The usage of angular2-markdown might be obsolete, if https://bugs.eclipse.org/bugs/show_bug.cgi?id=521891 is solved. See https://github.com/eclipse/orion.client/compare/silenio/Bug521891 for an initial shot for the refactoring of Eclipse Orion.

**Comment by koppor** [comment]
Follow up at https://github.com/eclipse/winery/pull/138

**Pull request closed without merging**
