### PR TITLE
Set readme-component as entry point

### PR DESCRIPTION
**Pull request by meyerpp**
Set readme-submenu as entry point for each component

grafik

- [x] Ensure that the commit message is [a good commit message](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by lharzenetter** [comment]
The issue regarding the Servicetemplates Design is already done by #158

**Comment by koppor** [comment]
Since `FrameTopLarge.jpg` already came in at another PR, please remove it here. It should not happen that the same change comes in two different PRs.

**Comment by meyerpp** [comment]
Removed Servicetemplates Design

**Pull request merged**
