### PR TITLE
[WIP] Service Template Inheritance

### PR DESCRIPTION
**Pull request by nyuuyn**
Added feature to set inheritance for Service Templates:
+ added custom attributes abstract, final and derivedFrom
+ added the inheritance resources and views into the service template resource and ui components.

Screenshot:
screen shot 2018-02-19 at 15 55 41

### CODE REVIEW

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by nyuuyn** [comment]
Hint: when you checkout the branch the ServiceTemplateResource has no conflicts.. ^^

**Comment by koppor** [comment]
Would it be OK if you follow the steps explained at http://eclipse.github.io/winery/dev/ToolChain#github---prepare-final-pull-request to create **one** commit with your changes only! You should reall, really base on `upstream/master`. I beg you! Please, please, please ensure that you setup `origin`  and `upstream` as described at http://eclipse.github.io/winery/dev/ToolChain#steps-to-initialize-the-repository.

**Comment by koppor** [comment]
Preparation PR is at https://github.com/OpenTOSCA/winery/pull/68

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by koppor** [comment]
Not fully finished. Focus is on other work. Will be reopened as soon as the focus is on these kind of tasks again.

**Pull request closed without merging**
