### PR TITLE
Fix typo in ADR

### PR DESCRIPTION
**Pull request by kevgo**
- [x] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request. Especially, we require **a single commit**
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files
- [ ] Ensure that you appear in `NOTICE` at Copyright Holders
- [x] Tests created for changes
- [x] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by genie-winery** [comment]
Can one of the admins verify this patch?

**Comment by Vogel612** [comment]
@kevgo Our automated check for the eclipse contributor agreement said that you did not yet sign the eca. Please check [this link](https://accounts.eclipse.org/legal/eca/validation/30744) for some next steps to sign the ECA. Thanks!

**Comment by kevgo** [comment]
Signed the ECA and added the "signed-off-by" footer to the commit message. Please take another look.

**Comment by Vogel612** [comment]
LGTM! Thanks for this :)

**Pull request merged**
