### PR TITLE
[WIP] Add inheritance to service templates

### PR DESCRIPTION
**Pull request by koppor**
Feature by @nyuuyn 

Enables setting abstract, derivedFrom and final attributes on Service Templates, just like on NodeTypes. Adds exporting of concrete ServiceTemplates when an abstract Service Template is exported (CSAR may have multiple Service Templates now)

TODO - all other features finished

## As is

grafik

## Should be 

grafik

### CODE REVIEW

**Comment by miwurster** [comment]
Is this something we (@lharzenetter and @miwurster) must finalize?
Btw, is this conform to the standard? ... both, XML and YAML?

**Comment by nyuuyn** [comment]
Well, yes and no, cause:

In the XML and YAML Standard you can substitute Service Templates (in XML: http://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.html#_Toc356403659) and Topology Template (YAML: https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969450) by a Node Type, and a Node Type can be abstract, final and derived and whatnot, atleast in the XML spec (yes, its a little fubar).

However, this feature is not standard-conform, so in other words, we can forget this feature. It was used to describe adapting services where an abstract service template was transformed/implemented by concrete one at runtime.

**Comment by miwurster** [comment]
@lharzenetter @koppor ... your pov?

**Comment by lharzenetter** [comment]
Yes, it is not standard conform and you can use the substitution, it is implemented almost with all features I guess.

**Comment by lharzenetter** [comment]
So we decided to close it, as it is 1. not standard conform and 2. we currently do not need this feature.

**Pull request closed without merging**
